In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
b = np.array([[1,2,3],[10,11,12]])

In [7]:
 b.shape  # it means that ther are 2 rows and 3 values in each row

(2, 3)

In [ ]:
b.shape[0] #give number of rows
b.shape[1] #give number of colonms

In [33]:
c = np.array([[1,2,3,6],[4,5,6,8]])

In [28]:
l = [[9,7,8,7],[1,2,3,4]]
l1 = [[8,8,8,8],[8,8,8,8]]
c

array([[9, 7, 8, 7],
       [1, 2, 3, 4]])

In [19]:
c[:,0] = 9 #assigning one list to second 

In [31]:
c[:]=l #assigning two nested lists two dim array

In [32]:
c

array([[9, 7, 8, 7],
       [1, 2, 3, 4]])

In [41]:
a = np.array([7,8,9])
b = np.array([[1,2,3],[4,5,6]])
m = a/b

In [42]:
m

array([[7.  , 4.  , 3.  ],
       [1.75, 1.6 , 1.5 ]])

In [65]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
arr[arr[:,:] > 2]

array([3, 4, 5, 6, 7, 8])

In [54]:
a.shape = (3,-1)

In [87]:
a1 = arr[0,0]
a2 = arr[0,:1].squeeze()
a3 = arr[:1,:1].squeeze()


In [101]:
type(a3)

numpy.ndarray

In [109]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [111]:
arr = gen(pcg())

In [120]:
arr.normal( size = (2,2))

array([[-1.22211144,  1.08582752],
       [ 1.68574444, -1.25240574]])

In [130]:
arr = gen(pcg(10))
arr.integers(low = 10 , high = 100 , size = (2,2))

array([[79, 96],
       [33, 28]], dtype=int64)

creating random application

In [136]:
creating random applicationarr = gen(pcg(seed = 365))
arr1 = arr.normal(loc = 2,scale =3,size = (1000))
arr2 = arr.normal(loc = 7,scale =3,size = (1000))
arr3= arr.logistic(loc = 11,scale =3,size = (1000))
arr4 = arr.exponential(scale = 4,size = (1000))
arr5 = arr.geometric(p = 0.7,size = (1000))

In [146]:
r = np.array([arr1,arr2,arr3,arr4,arr5])
r.shape

(5, 1000)

In [149]:
a = r.transpose()
a.shape

(1000, 5)

In [3]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

In [12]:
np.concatenate([a,b], axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [14]:
a = np.array([1,2,3])

In [22]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [43]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,5])

In [30]:
np.setdiff1d(a,b,assume_unique=True)

array([1, 2, 3, 4])

In [46]:
np.where(a == b)[0][0]

4

In [62]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [73]:
arr = np.arange(9).reshape(3,3)

In [74]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
np.random.uniform(low=5, high=10, size=(5,3))

array([[5.55637133, 7.17651001, 6.81876792],
       [6.05599829, 8.56469491, 9.73793063],
       [8.12431458, 6.22468654, 6.61701755],
       [6.81460934, 7.24206013, 9.9799165 ],
       [6.97970894, 8.53353794, 7.49575195]])

In [95]:
a = np.random.randint(low=5, high=10, size=(5,3))+np.random.random((5,3))

In [97]:
np.round(a,decimals = 3)

array([[8.706, 8.279, 6.221],
       [7.792, 9.238, 5.048],
       [9.898, 6.582, 7.139],
       [6.43 , 9.41 , 9.298],
       [9.139, 5.61 , 7.651]])

In [163]:
np.set_printoptions(threshold=6)

In [132]:
a = np.arange(15)

In [165]:
np.set_printoptions(threshold = np.inf)

In [167]:
a = np.arange(15)

In [168]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2, ..., 12, 13, 14])

In [154]:
b = np.arange(10)

In [170]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [171]:
iris = np.gefromtxt(url, delimiter=',', dtype='object')


In [172]:
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


In [187]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [197]:
species = np.array([row[4] for row in iris])

In [200]:
species

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

In [263]:
l = list(np.array(species).reshape(2,-1)[:4,:4][:3][0])


In [264]:
l

[b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa']

In [225]:
i = np.array([row.tolist() for row in iris])

In [231]:
i[:2,:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2'],
       [b'4.9', b'3.0', b'1.4', b'0.2']], dtype='|S15')

In [260]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [277]:
np.set_printoptions(suppress = True)


In [278]:
species = np.array([row[4] for row in iris])

In [288]:
[i.decode('utf-8') for i in species]


['Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
